import { ArrowRight, BookOpen, Building2, Globe2, HandHeart, HeartHandshake, Leaf, Sparkles, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { useSiteLanguage } from "../components/SiteLanguage";

const base = import.meta.env.BASE_URL;
type Copy = { ko: string; en: string };
const text = (value: Copy, english: boolean) => value[english ? "en" : "ko"];

const programs = [
  { number: "01", icon: HandHeart, title: { ko: "꿈을 보듬다", en: "Nurture dreams" }, description: { ko: "어려움에 놓인 이웃이 자신의 가능성을 잃지 않고 다시 설 수 있도록 돕습니다.", en: "We help neighbors facing hardship rediscover their possibilities and stand again." }, tags: [{ ko: "취약계층 지원", en: "Community support" }, { ko: "장학·멘토링", en: "Scholarships & mentoring" }, { ko: "장애예술인", en: "Artists with disabilities" }] },
  { number: "02", icon: Users, title: { ko: "시민을 키우다", en: "Grow citizens" }, description: { ko: "시민이 사실을 알고 스스로 판단하며 공동체 문제에 참여할 힘을 키웁니다.", en: "We build citizens’ capacity to know the facts, make their own judgments, and engage in community issues." }, tags: [{ ko: "시민교육", en: "Civic education" }, { ko: "미디어 문해력", en: "Media literacy" }, { ko: "시민 아카데미", en: "Civic academy" }] },
  { number: "03", icon: Globe2, title: { ko: "세계와 잇다", en: "Connect with the world" }, description: { ko: "문화와 협력을 통해 국경을 넘어 사람과 가능성을 연결합니다.", en: "Through culture and collaboration, we connect people and possibilities across borders." }, tags: [{ ko: "국제협력", en: "International cooperation" }, { ko: "문화교류", en: "Cultural exchange" }, { ko: "개발협력", en: "Development cooperation" }] },
];
const stories = [
  { label: { ko: "장애예술", en: "DISABILITY ARTS" }, title: { ko: "발달장애 미술작가들의 작품을 시민과 만나다", en: "Bringing artists with developmental disabilities together with the public" }, summary: { ko: "다섯 명의 발달장애 미술작가와 함께 야외 전시와 시민 참여형 예술 프로그램을 진행했습니다.", en: "With five artists with developmental disabilities, we held an outdoor exhibition and participatory arts programs." }, image: `${base}images/kumepume/programs/disability-art-2024.webp`, alt: { ko: "2024년 발달장애 미술작가 전시회 현장", en: "2024 exhibition by artists with developmental disabilities" }, href: "/activities/disability-art-exhibition-2024" },
  { label: { ko: "청소년 문화예술", en: "YOUTH ARTS" }, title: { ko: "다문화·고려인 청소년이 K-POP으로 가능성을 찾다", en: "Multicultural and Koryo-in youth find possibilities through K-pop" }, summary: { ko: "보컬과 댄스, 문화산업 교육을 통해 서로의 배경을 존중하고 자신의 재능을 발견했습니다.", en: "Through vocal, dance, and cultural-industry education, young people honored one another’s backgrounds and discovered their talents." }, image: `${base}images/kumepume/programs/multicultural-kpop-2023.webp`, alt: { ko: "2023년 다문화청소년 K-POP 아카데미 현장", en: "2023 multicultural youth K-pop academy" }, href: "/activities/multicultural-youth-kpop-academy-2023" },
  { label: { ko: "국제 문화교류", en: "CULTURAL EXCHANGE" }, title: { ko: "키르기스스탄 고려인과 ‘우리는 하나’를 나누다", en: "Sharing ‘We are one’ with Koryo-in communities in Kyrgyzstan" }, summary: { ko: "고려인 단체와 함께 문화공연과 교류를 진행하고 지속적인 협력 기반을 만들었습니다.", en: "We held cultural performances and exchanges with Koryo-in groups, laying a foundation for continued collaboration." }, image: `${base}images/kumepume/programs/kyrgyzstan-exchange-2023.webp`, alt: { ko: "2023년 키르기스스탄 고려인 문화교류 참가자들", en: "Participants in the 2023 Kyrgyzstan cultural exchange" }, href: "/activities/kyrgyzstan-cultural-exchange-2023" },
];

export default function Home() {
  const { language } = useSiteLanguage();
  const english = language === "en";
  const quickLinks = english ? [["About us", "The change KUMEPUME seeks", "/about"], ["Programs", "People · citizens · world", "/programs"], ["Activities & impact", "Change in numbers and in the field", "/activities"], ["Get involved", "Giving · volunteering · partnerships", "/join"], ["Transparency", "Bylaws · disclosure · reports", "/transparency"]] : [["단체 소개", "꿈에품에가 지향하는 변화", "/about"], ["주요 사업", "사람·시민·세계", "/programs"], ["활동과 성과", "숫자와 현장으로 보는 변화", "/activities"], ["함께하기", "후원·봉사·기업협력", "/join"], ["투명경영", "정관·공시·연차보고", "/transparency"]];
  const impact = english ? [["₩352.33M", "Public-interest spending in 2023"], ["5", "Public-interest programs in 2023"], ["126", "Full members as of 2024"], ["5", "Staff members as of 2024"]] : [["3억 5,233만원", "2023년 공익목적사업 지출"], ["5개", "2023년 공익목적사업"], ["126명", "2024년 기준 정회원"], ["5명", "2024년 기준 실무진"]];
  const principles = english ? [["01", "We disclose goals first", "We make clear from the start what each project aims to change."], ["02", "We record process and numbers", "Participation, spending, and change in the field remain verifiable."], ["03", "We connect to next steps", "We share outcomes and limits, then improve the work."]] : [["01", "목표를 먼저 공개합니다", "무엇을 바꾸려는 사업인지 시작부터 분명히 밝힙니다."], ["02", "과정과 숫자를 기록합니다", "참여와 지출, 현장의 변화를 확인 가능한 자료로 남깁니다."], ["03", "다음 행동으로 연결합니다", "성과와 한계를 함께 공개하고 더 나은 사업으로 개선합니다."]];
  const joinCards = english ? [[HeartHandshake, "Donate", "Sustain change with a recurring or one-time gift."], [Sparkles, "Share your skills", "Connect your expertise and experience where they are needed."], [Building2, "Partner with us", "Turn corporate social responsibility into lasting programs."], [Users, "Volunteer", "Plan civic action with people who want to take part."]] : [[HeartHandshake, "후원하기", "정기·일시 후원으로 변화를 이어갑니다."], [Sparkles, "재능기부", "전문성과 경험을 필요한 현장에 연결합니다."], [Building2, "기업협력", "기업의 사회공헌을 지속가능한 사업으로 만듭니다."], [Users, "공익봉사", "시민이 직접 참여하는 행동을 함께 기획합니다."]];
  const heroLines = english ? ["Growing dreams", "Nurturing possibilities", "Growing citizens"] : ["꿈을 키우고", "품을 키웁니다", "시민이 자랍니다"];
  return <div className="kumepume-home">
    <section className="kumepume-hero" aria-labelledby="hero-title"><img src={`${base}images/kumepume/hero-children-garden-2026.webp`} alt={english ? "Children exploring nature together in a sunlit garden" : "햇살이 드는 정원에서 함께 자연을 살펴보는 아이들"} className="kumepume-hero-image size-full object-cover" /><div className="kumepume-hero-copy container-page z-10 flex items-end pb-20 pt-16 sm:pb-24 lg:pb-28"><h1 id="hero-title" className="kumepume-hero-slogan text-[clamp(1.025rem,2.625vw,2.6rem)] font-black leading-[1.32] tracking-[-.06em] text-white">{heroLines.map((line) => <span key={line} className="kumepume-hero-slogan-line block whitespace-nowrap">{line}</span>)}</h1></div></section>
    <nav className="border-y border-[#183b33]/10 bg-white" aria-label={english ? "Homepage links" : "메인페이지 바로가기"}><div className="container-page grid sm:grid-cols-2 lg:grid-cols-5">{quickLinks.map(([label, detail, href], index) => <Link key={label} to={href} className={`group flex min-h-[112px] items-center justify-between gap-4 py-6 transition hover:bg-[#f2f7ed] sm:px-6 ${index > 0 ? "border-t border-[#183b33]/10 sm:border-t-0 lg:border-l" : ""} ${index === 2 || index === 4 ? "sm:border-l lg:border-l" : ""}`}><span><strong className="block text-base font-black text-[#183b33]">{label}</strong><small className="mt-1.5 block text-xs leading-5 text-charcoal/48">{detail}</small></span><ArrowRight className="shrink-0 text-[#e47716] transition group-hover:translate-x-1" size={18}/></Link>)}</div></nav>
    <section id="work" className="scroll-mt-32 bg-white py-20 sm:py-24"><div className="container-page"><div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><p className="kumepume-eyebrow">WHAT WE DO</p><h2 className="kumepume-section-title">{english ? "Nurturing lives and the power of citizens" : "삶을 보듬고, 시민의 힘을 키웁니다"}</h2></div><p className="max-w-2xl text-base leading-8 text-charcoal/60">{english ? "Our three programs move beyond support toward independence, and beyond information toward civic judgment and action." : "지원에 머물지 않고 자립으로, 정보에 머물지 않고 시민의 판단과 행동으로 이어지는 세 가지 사업을 펼칩니다."}</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-sm bg-[#183b33]/15 sm:grid-cols-2 xl:grid-cols-3">{programs.map(({ number, icon: Icon, title, description, tags }) => <article key={title.ko} className="group min-h-[360px] bg-[#fffdf8] p-7 transition duration-300 hover:bg-[#f2f7ed] sm:p-8"><div className="flex items-center justify-between"><span className="text-xs font-black tracking-[.18em] text-charcoal/35">{number}</span><span className="grid size-12 place-items-center rounded-full bg-[#dfeccd] text-[#285748] transition group-hover:bg-[#e88920] group-hover:text-white"><Icon size={22}/></span></div><h3 className="mt-12 text-2xl font-black tracking-[-.035em] text-[#183b33]">{text(title, english)}</h3><p className="mt-4 text-[15px] leading-7 text-charcoal/62">{text(description, english)}</p><div className="mt-7 flex flex-wrap gap-2">{tags.map((tag) => <span key={tag.ko} className="rounded-full border border-[#183b33]/15 px-3 py-1.5 text-xs font-bold text-[#183b33]/70">{text(tag, english)}</span>)}</div></article>)}</div></div></section>
    <section id="impact" className="scroll-mt-32 bg-[#183b33] py-20 text-white sm:py-24"><div className="container-page"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="text-xs font-black tracking-[.2em] text-[#ffc04c]">OUR IMPACT</p><h2 className="mt-5 text-4xl font-black leading-tight tracking-[-.045em] sm:text-5xl">{english ? <>So good intentions<br/>become lasting change</> : <>좋은 뜻이<br/>변화로 남도록</>}</h2><p className="mt-5 max-w-lg text-base leading-8 text-white/65">{english ? "We record not only how much we spend, but whose lives change, how they change, and how long that change lasts." : "우리는 얼마를 썼는지만이 아니라 누구의 삶이 어떻게 달라졌는지, 그 변화가 얼마나 지속되는지를 기록하겠습니다."}</p></div><div className="grid gap-px overflow-hidden rounded-sm bg-white/15 sm:grid-cols-2">{impact.map(([value, label]) => <div key={label} className="bg-white/[.045] p-7 sm:p-9"><strong className="block text-3xl font-black tracking-[-.04em] text-[#ffc04c] sm:text-4xl">{value}</strong><span className="mt-3 block text-sm font-bold text-white/70">{label}</span></div>)}</div></div><div className="mt-10 grid gap-4 border-t border-white/15 pt-8 md:grid-cols-3">{principles.map(([number, title, description]) => <div key={number} className="grid grid-cols-[auto_1fr] gap-4 py-2"><span className="text-xs font-black tracking-[.15em] text-[#ffc04c]">{number}</span><div><strong className="block text-base font-black">{title}</strong><p className="mt-2 text-sm leading-6 text-white/55">{description}</p></div></div>)}</div><p className="mt-7 text-xs text-white/38">{english ? "※ Based on public-interest corporation disclosures and 2024 organization records" : "※ 공익법인 결산 공시 및 2024년 단체현황 자료 기준"}</p></div></section>
    <section id="stories" className="scroll-mt-32 bg-[#f4f0e7] py-20 sm:py-24"><div className="container-page"><p className="kumepume-eyebrow">CHANGE STORIES</p><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><h2 className="kumepume-section-title">{english ? "Change begins with people and places" : "변화는 사람과 현장에서 시작됩니다"}</h2><Link to="/activities" className="inline-flex items-center gap-2 text-sm font-black text-[#183b33]">{english ? "View all activity records" : "활동 기록 전체 보기"} <ArrowRight size={17}/></Link></div><div className="mt-12 grid gap-6 lg:grid-cols-3">{stories.map((story) => <Link to={story.href} key={story.href} className="group overflow-hidden bg-white"><div className="aspect-[4/3] overflow-hidden"><img src={story.image} alt={text(story.alt, english)} className="size-full object-cover transition duration-700 group-hover:scale-[1.035]"/></div><div className="p-7"><p className="text-xs font-black tracking-[.14em] text-[#e47716]">{text(story.label, english)}</p><h3 className="mt-3 text-2xl font-black leading-8 tracking-[-.035em] text-[#183b33]">{text(story.title, english)}</h3><p className="mt-4 text-[15px] leading-7 text-charcoal/60">{text(story.summary, english)}</p></div></Link>)}</div></div></section>
    <section id="seed-voice" className="scroll-mt-32 bg-white py-20 sm:py-24"><div className="container-page"><div className="grid overflow-hidden rounded-sm border border-[#183b33]/12 lg:grid-cols-[1fr_.86fr]"><div className="flex flex-col justify-center bg-[#eef3e7] p-8 sm:p-12 lg:p-16"><div className="flex items-center gap-3"><BookOpen className="text-[#e88920]" size={26}/><p className="kumepume-eyebrow">PUBLIC INTEREST MEDIA</p></div><h2 className="mt-6 text-4xl font-black leading-tight tracking-[-.045em] text-[#183b33] sm:text-5xl">{english ? <>A civic voice<br/>protecting the public good</> : <>공익을 지키는<br/>시민의 목소리</>}</h2><p className="mt-6 max-w-xl text-base leading-8 text-charcoal/65">{english ? "SEED VOICE is an independent civic journal that expands the public’s right to know and access to public-interest information, while monitoring power in government and civil society." : "씨앗의 소리는 시민의 알 권리와 공익정보 접근을 넓히고 국가와 시민사회 권력을 감시하는 독립 시민저널입니다."}</p><a href="https://seedvoice.kr" target="_blank" rel="noreferrer" className="mt-8 inline-flex w-fit items-center gap-2 border-b-2 border-[#183b33] pb-1 text-sm font-black text-[#183b33]">{english ? "Visit SEED VOICE" : "씨앗의 소리 바로가기"} <ArrowRight size={17}/></a></div><div className="relative min-h-[390px] bg-[#183b33] p-8 text-white sm:p-12 lg:p-16"><div className="absolute right-7 top-7 opacity-15"><Leaf size={130} strokeWidth={1.2}/></div><p className="text-xs font-black tracking-[.18em] text-[#ffc04c]">KUMEPUME PROJECT</p><p className="relative mt-20 max-w-md text-3xl font-black leading-[1.35] tracking-[-.035em]">{english ? <>The power to know facts,<br/>to judge for ourselves,<br/>and to act together</> : <>사실을 아는 힘,<br/>스스로 판단하는 힘,<br/>함께 행동하는 힘</>}</p><p className="relative mt-7 max-w-md text-sm leading-7 text-white/62">{english ? "Editorial decisions are made independently under separate editorial principles." : "편집과 기사 판단은 별도의 편집원칙에 따라 독립적으로 이루어집니다."}</p></div></div></div></section>
    <section id="join" className="scroll-mt-32 bg-[#ef901f] py-20 sm:py-24"><div className="container-page"><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="text-xs font-black tracking-[.2em] text-[#183b33]/60">JOIN KUMEPUME</p><h2 className="mt-5 text-4xl font-black leading-tight tracking-[-.045em] text-[#183b33] sm:text-5xl">{english ? <>What you have<br/>can strengthen the public good</> : <>당신이 가진 것이<br/>공익의 힘이 됩니다</>}</h2><p className="mt-5 max-w-xl text-base font-medium leading-8 text-[#183b33]/72">{english ? "You can join us not only with funding, but with time, experience, expertise, and connections." : "후원뿐 아니라 시간, 경험, 전문성과 연결의 힘으로 함께할 수 있습니다."}</p></div><div className="grid gap-3 sm:grid-cols-2">{joinCards.map(([Icon, title, description], index) => { const JoinIcon = Icon as typeof HeartHandshake; const href = ["/join/donate", "/join/volunteer", "/join/corporate", "/join/member"][index]; return <Link to={href} key={title as string} className="group bg-white/92 p-6 transition hover:-translate-y-1 hover:bg-white"><JoinIcon size={24} className="text-[#e47716]"/><strong className="mt-5 block text-xl font-black text-[#183b33]">{title as string}</strong><span className="mt-2 block text-sm leading-6 text-charcoal/58">{description as string}</span><ArrowRight className="mt-5 text-[#183b33] transition group-hover:translate-x-1" size={18}/></Link> })}</div></div></div></section>
    <section id="transparency" className="scroll-mt-32 bg-white py-16 sm:py-20"><div className="container-page grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="kumepume-eyebrow">TRUST & TRANSPARENCY</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em] text-[#183b33] sm:text-4xl">{english ? "The public good grows on trust" : "공익은 신뢰 위에서 자랍니다"}</h2><p className="mt-4 max-w-2xl text-base leading-8 text-charcoal/60">{english ? "We will make our bylaws, use of donations, financial records, and program results easy for everyone to see." : "정관, 기부금 사용 내역, 결산서류와 사업성과를 누구나 쉽게 확인할 수 있도록 공개하겠습니다."}</p></div><div className="flex flex-wrap gap-3"><Link to="/transparency" className="kumepume-button-secondary">{english ? "View transparency" : "투명경영 보기"}</Link><Link to="/transparency/reports" className="kumepume-button-primary">{english ? "Annual reports" : "연차보고서"}</Link></div></div></section>
  </div>;
}
