import { ArrowLeft, ArrowRight, CalendarDays, ExternalLink } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { legacyStories } from "../data/kumepume/legacyStories";

function asset(path: string) { return `${import.meta.env.BASE_URL}${path.replace(/^\//, "")}`; }

export default function LegacyStoryDetail() {
  const { storyId } = useParams();
  const item = legacyStories.find((story) => story.id === storyId);
  if (!item) return <div className="container-page py-24"><h1 className="text-4xl font-black text-[#183b33]">기록을 찾을 수 없습니다</h1><Link to="/stories/archive" className="kumepume-button-primary mt-8"><ArrowLeft size={16}/>목록으로</Link></div>;
  const related = legacyStories.filter((story) => story.id !== item.id && story.category === item.category).slice(0, 3);
  return <article className="bg-[#fffdf8]">
    <header className="border-b border-[#183b33]/10 bg-[#f3efe6] py-16 sm:py-20"><div className="article-content-frame"><Link to="/stories/archive" className="inline-flex items-center gap-2 text-sm font-black text-[#183b33]/60 hover:text-[#183b33]"><ArrowLeft size={16}/>과거 기록</Link><div className="mt-10 flex flex-wrap items-center justify-center gap-3 text-xs font-black"><span className="rounded-full bg-[#183b33] px-3 py-1.5 text-white">{item.category}</span><span className="inline-flex items-center gap-1.5 text-charcoal/45"><CalendarDays size={14}/>{item.dateLabel}</span>{item.author && <span className="text-charcoal/45">글 {item.author}</span>}</div><h1 className="article-detail-title mt-6">{item.title}</h1><p className="article-summary text-center">{item.summary}</p></div></header>
    <div className="article-content-frame py-12 sm:py-16"><figure className="reading-column overflow-hidden bg-[#e8eee1]"><img src={asset(item.image)} alt={item.imageAlt} className="max-h-[680px] w-full object-contain"/><figcaption className="border-t border-[#183b33]/10 bg-white px-5 py-3 text-xs leading-5 text-charcoal/48">{item.imageAlt} · 기존 꿈에품에 홈페이지 원본의 화면용 복사본</figcaption></figure><div className="reading-column mt-8 border-l-4 border-[#ef901f] bg-[#fff4df] px-6 py-5 text-sm font-bold leading-7 text-[#183b33]">이 페이지는 기존 홈페이지의 과거 기록을 원문 기준으로 이전한 것입니다. 당시의 직함·수치·협력관계·사업계획은 현재 정보가 아니며, 최신 사실로 해석하지 않습니다.</div><div className="reading-column mt-10">{item.paragraphs.map((paragraph, index) => <p key={index} className="article-copy article-copy-long whitespace-pre-line">{paragraph}</p>)}</div>{item.references && <div className="reading-column mt-10 bg-[#f2f5ec] px-6 py-5"><p className="text-xs font-black tracking-[.14em] text-[#e47716]">확인 자료</p><div className="mt-3 grid gap-2">{item.references.map((reference) => <a key={reference.url} href={reference.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-black text-[#183b33]">{reference.label} <ExternalLink size={14}/></a>)}</div></div>}<div className="reading-column mt-12 flex flex-wrap items-center justify-between gap-4 border-t border-[#183b33]/12 pt-7"><p className="text-xs leading-6 text-charcoal/42">원문·원본 이미지·기존 주소는 별도 보존되어 있습니다.</p><a href={item.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-black text-[#183b33]">기존 페이지 보기 <ExternalLink size={15}/></a></div></div>
    {related.length > 0 && <section className="bg-[#f2f5ec] py-16 sm:py-20"><div className="container-page"><div className="flex items-end justify-between gap-5"><div><p className="kumepume-eyebrow">RELATED ARCHIVE</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em] text-[#183b33]">같은 분류의 기록</h2></div><Link to="/stories/archive" className="hidden items-center gap-2 text-sm font-black text-[#183b33] sm:inline-flex">전체 보기 <ArrowRight size={16}/></Link></div><div className="mt-9 grid gap-5 md:grid-cols-3">{related.map((story) => <Link key={story.id} to={`/stories/archive/${story.id}`} className="group bg-white p-5"><div className="aspect-[16/10] overflow-hidden bg-[#e8eee1]"><img src={asset(story.image)} alt={story.imageAlt} className="size-full object-cover transition duration-500 group-hover:scale-[1.035]"/></div><p className="mt-5 text-xs font-black text-[#e47716]">{story.dateLabel}</p><h3 className="mt-2 text-lg font-black leading-7 text-[#183b33]">{story.title}</h3></Link>)}</div></div></section>}
  </article>;
}
